### PR TITLE
Pulled the authentication selector out of the hidden pane for greater visibility and ease of selection

### PR DESCRIPTION
**Pull request by raydenl**

### CODE REVIEW

**Comment by raydenl** [comment]
Also added a clear auth button in the authentication pane

**Comment by stajs** [comment]
Let me just get updates/releases moved over to GitHub, then I'll look at merging these in.

**Comment by stajs** [comment]
See #47

**Comment by stajs** [comment]
@raydenl Waiting on :shipit: before taking out of prerelease.

**Comment by stajs** [comment]
:shipit:

**Pull request merged**
