### PR TITLE
Enable the auto-refresh authentication option

### PR DESCRIPTION
**Pull request by lianwanggit**
Refresh Auth:
  - There is a new back-end service running in a non-UI thread
  - The service scans all auth tokens every 1 minutes
  - If the token is expired or the token will expire within 3 minutes, it does auto-refresh the authentication
  - As long as the auth gets updated, UI thread get notification of  the updated token.

### CODE REVIEW

**Comment by stajs** [comment]
Waiting on #68.

**Comment by stajs** [comment]
#68 resolved, waiting on #71.

**Comment by nicojclic** [comment]
#71 is complete, is this available to merge now?

**Comment by stajs** [comment]
https://github.com/lic-nz/Malone/pull/69#issuecomment-183973305

**Comment by stajs** [comment]
@lianwanggit Can you re-submit and target the `develop` branch?

cc @VladMukhitdinovLic

**Comment by stajs** [comment]
Some quick thoughts:

- What does the UX look like for this?
- I'm not sure that auto-refreshing is the best approach, unless it is opt-in/out. You may want to actually have a test with expired tokens.
- I'm not sure that auto-scanning is a good idea either, it could be wasteful? I imagined it would be more on-demand: as a request is initiated, refresh the token at that point if required.
- I would be interested to know how you communicate the token updates through the UI.
- If we extended Malone in the future to support other auth mechanisms, would this be modularizable?

**Comment by lianwanggit** [comment]
1. In [Add Token] page, there is an option to enable/disable Auto-refresh
2. If enabling Auto-refresh, the background task will request and renew token repeatedly. From the users point of view, the token never expires.
3. Auto-scanning works also on demand, it only refresh the tokens which are expired or will in a short interval (configurable). Anyway, your idea sounds better
4. The token-auto-refresh-service keeps the cache of all tokens and notifies UI if anything changes by its refreshing
5. Of course, the current service relies on OAuthApplication, should be extendable for generic auth applications.

**Comment by lianwanggit** [comment]
It RP is discarded. Please refer to new PR -  Autorefresh #84

**Comment by stajs** [comment]
Thanks

**Pull request closed without merging**
