### PR TITLE
Append env marker to Url indicating the access environment by the new…

### PR DESCRIPTION
**Pull request by lianwanggit**
It detects the changes of URL, and then append the env mark to Url:
  - All configurable by the new config file: env-marker.json, which will be created with the default settings if it does not exist
  - Two match mode: Strict – match the input domain with the RootUrl list in config; Loose (default) – Match the input domain with keywords

### CODE REVIEW

**Comment by stajs** [comment]
Waiting on #68.

**Comment by stajs** [comment]
#68 resolved, waiting on #71.

**Comment by nicojclic** [comment]
#71 is complete, is this available to merge now?

**Comment by stajs** [comment]
https://github.com/lic-nz/Malone/pull/69#issuecomment-183973305

**Pull request merged**
